name: CI
on: [push, pull_request]
permissions:
  contents: read
env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, nightly, macos, win64, mingw]
        include:
          - build: stable
            os: ubuntu-26.04
            rust: stable
          - build: nightly
            os: ubuntu-26.04
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
          - build: win64
            os: windows-latest
            rust: stable-x86_64-pc-windows-msvc
          - build: mingw
            os: windows-latest
            rust: stable-x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Compile
        run: cargo check --all

      - name: Test
        run: cargo nextest run --all --no-tests warn

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add rustfmt
      - run: cargo fmt -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --verbose
  doc:
    name: Check Documentation
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add rust-docs
      - uses: Swatinem/rust-cache@v2
      - name: Run rustdoc
        run: cargo doc --verbose
  features:
    name: Feature check
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update nightly --no-self-update
          rustup default nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose -Z avoid-dev-deps
